/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#7b2f00",
        "surface-container-highest": "#e1e3e4",
        tertiary: "#5f2200",
        "secondary-fixed-dim": "#afcbd8",
        "surface-bright": "#f8f9fa",
        "surface-container-low": "#f3f4f5",
        "surface-container": "#edeeef",
        "on-primary-container": "#9abef9",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#ffb694",
        surface: "#f8f9fa",
        error: "#ba1a1a",
        secondary: "#48626e",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#d5e3ff",
        "secondary-fixed": "#cbe7f5",
        primary: "#043568",
        "on-secondary-fixed-variant": "#304a55",
        "on-primary": "#ffffff",
        "secondary-container": "#cbe7f5",
        "error-container": "#ffdad6",
        "surface-dim": "#d9dadb",
        "on-secondary-container": "#4e6874",
        "tertiary-container": "#833301",
        "surface-variant": "#e1e3e4",
        "inverse-primary": "#a7c8ff",
        "outline-variant": "#c2c6d3",
        "inverse-surface": "#2e3132",
        "primary-container": "#264c80",
        "on-tertiary-container": "#ffa77e",
        "on-primary-fixed": "#001b3c",
        "surface-tint": "#3a5f94",
        "primary-fixed-dim": "#a7c8ff",
        "surface-container-lowest": "#ffffff",
        "on-background": "#191c1d",
        outline: "#737783",
        "surface-container-high": "#e7e8e9",
        "on-primary-fixed-variant": "#1f477b",
        "on-secondary-fixed": "#021f29",
        background: "#f8f9fa",
        "on-surface-variant": "#424751",
        "on-tertiary-fixed": "#351000",
        "inverse-on-surface": "#f0f1f2",
        "on-error": "#ffffff",
        "tertiary-fixed": "#ffdbcc",
        "on-secondary": "#ffffff",
        "on-surface": "#191c1d",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
